PUT /users/1
Authorization: Bearer <JWT_TOKEN>
Content-Type: application/json

{
  "nickname": "새닉네임",
  "password": "새비밀번호123"
}


###

POST http://localhost:3000/sign-up
Content-Type: application/json

{
  "email": " ",
  "password": " ",
  "nickname": " "
}