@token= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpYXQiOjE3NTQyODMxNjAsImV4cCI6MTc1NDM2OTU2MH0.DR0zqsJAW4fMsY7-N4b8vJugfuh8gDVMU_P8k0zqhYc

###향수등록
POST http://localhost:4000/perfumes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  //"user_id": 2,
  "perfumeName": "channel no 5",
  "brandName": "channel",
  "content": "상큼 시원한 ",
  "tag": "여성, 시원함",
  "emotionTag": "사랑",
  "isPublic": "Y",
  "price": 100000,
  "point": 5,
  "notes": [
    { "noteType": "TOP", "noteName": "1번향" },
    { "noteType": "MIDDLE", "noteName": "2번향" },
    { "noteType": "BASE", "noteName": "3번향" }
  ],
  "images": [
    { "url_path": "" }
  ]
  
}


###{ "url": "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dwa006a0c8/Y0685240/Y0685240_F068522009_E01_ZHC.jpg?sw=1920" }

### 향수정보 삭제 (Delete Use) - 토큰 필요
DELETE http://localhost:4000/perfumes/9
Authorization: Bearer {{token}}

### 향수 상세 조회 (Get Perfume By ID)
GET http://localhost:4000/perfumes/9
Authorization: Bearer {{token}}

### 향수 목록 조회 (Get All Perfumes)
GET http://localhost:4000/perfumes/public
###Authorization: Bearer {{token}}

### 향수 정보 수정 (Update Perfume) - 토큰 필요
PUT http://localhost:4000/perfumes/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  //"perfumeId": 1,
  "perfumeName": "Dior Sauvage 3",
  "brandName": "Dior3",
  "content": "상쾌하고 시원한 향3",
  "tag": "남성, 시원함3",
  "emotionTag": "자유로움3",
  "isPublic": "Y",
  "price": 150000,
  "point": 4,
  "notes": [
    { "noteType": "TOP", "noteName": "Bergamot 수정3" },
    { "noteType": "MIDDLE", "noteName": "Lavender 수정3" },
    { "noteType": "BASE", "noteName": "Amber 수정3" }
  ],
  "images": [
    { "url_path": "https://www.dior.com3" }
  ]
}


### 회원가입 (Signup)
POST http://localhost:4000/users/signup
Content-Type: application/json

{
  "email": "user5@example.com",
  "password": "password123",
  "nickname": "으하하333"
}

### 로그인 (Login)
POST http://localhost:4000/users/login
Content-Type: application/json

{
  "email": "user2@example.com",
  "password": "password123"
}

### 회원정보 수정 (Update User) - 토큰 정상
PUT http://localhost:4000/users/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nickname": "으하하수정함",
  "password": "password123"
}


### 회원정보 조회 (Get User By ID) - 토큰
GET http://localhost:4000/users/2
Authorization: Bearer {{token}}

### 닉네임으로 사용자 조회 (Find User By Nickname) - 토큰
GET http://localhost:4000/users/findUser/으하하
Authorization: Bearer {{token}}

### 회원 탈퇴 (Delete User) - 토큰
DELETE http://localhost:4000/users/1
Authorization: Bearer {{token}}

