-- CreateTable
CREATE TABLE `PERFUME_INFO` (
    `PERFUME_ID` INTEGER NOT NULL,
    `USER_ID` INTEGER NOT NULL,
    `PERFUME_NAME` VARCHAR(191) NULL,
    `BRAND_NAME` VARCHAR(191) NULL,
    `CONTENT` VARCHAR(191) NULL,
    `TAG` VARCHAR(191) NULL,
    `EMOTION_TAG` VARCHAR(191) NULL,
    `POINT` INTEGER NULL,
    `IS_PUBLIC` VARCHAR(191) NULL,
    `PERFUME_STATUS` VARCHAR(191) NULL,
    `CREATE_AT` DATETIME(3) NULL,
    `UPDATE_AT` DATETIME(3) NULL,

    PRIMARY KEY (`PERFUME_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PERFUME_IMG` (
    `PERFUME_ID` INTEGER NOT NULL,
    `URL` VARCHAR(191) NULL,

    PRIMARY KEY (`PERFUME_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PERFUME_NOTE` (
    `PN_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `PERFUME_ID` INTEGER NOT NULL,
    `NOTE_TYPE` ENUM('TOP', 'MIDDLE', 'BASE') NULL,
    `NOTE_NAME` VARCHAR(191) NULL,

    PRIMARY KEY (`PN_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `FOLLOWINGLIST` (
    `USER_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `FLOW_ID` INTEGER NULL,
    `FLOW_STATUS` VARCHAR(191) NULL,
    `CREATE_AT` DATETIME(3) NULL,
    `UPDATE_AT` DATETIME(3) NULL,

    PRIMARY KEY (`USER_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `USER_INFO` (
    `USER_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `EMAIL` VARCHAR(191) NULL,
    `PASSWORD` VARCHAR(191) NULL,
    `NICKNAME` VARCHAR(191) NULL,
    `USER_STATUS` ENUM('Y', 'N') NULL,

    PRIMARY KEY (`USER_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `PERFUME_INFO` ADD CONSTRAINT `PERFUME_INFO_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `USER_INFO`(`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PERFUME_IMG` ADD CONSTRAINT `PERFUME_IMG_PERFUME_ID_fkey` FOREIGN KEY (`PERFUME_ID`) REFERENCES `PERFUME_INFO`(`PERFUME_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PERFUME_NOTE` ADD CONSTRAINT `PERFUME_NOTE_PERFUME_ID_fkey` FOREIGN KEY (`PERFUME_ID`) REFERENCES `PERFUME_INFO`(`PERFUME_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `FOLLOWINGLIST` ADD CONSTRAINT `FOLLOWINGLIST_USER_ID_fkey` FOREIGN KEY (`USER_ID`) REFERENCES `USER_INFO`(`USER_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
